### ISSUE TITLE
[TASK] verifyIdentity method on Semaphore.ts

### ISSUE THREAD

**Issue by semaraugusto** [webb-tools/semaphore-anchor#13]
**Is your feature request related to a problem? Please describe.**
Creating a proof for the verifyProof contract call requires too much pre-processing from the user. By providing a method verifyIdentity we can abstract away the proof generation from the user and only require him to provide the needed parameters.

**Describe the solution you'd like**
An interface like this would allow users to create proofs for both current chain and an external chain by using the optional parameter `externalGroup`.
```
  public async verifyIdentity(
    identity: Identity,
    signal: string,
    groupId: number,
    chainId: number,
    externalNullifier: BigNumberish,
    externalGroup?: LinkedGroup
  ): Promise<ContractTransaction>
```

**Comment by dutterbutter** [comment]
Closed in https://github.com/webb-tools/semaphore-anchor/pull/10
