### ISSUE TITLE
[TASK] implement usage of `packages/semaphore` into unit and functional tests

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/semaphore-anchor#3]
### Task Checklist

- [ ] Implement usage of `packages/semaphore` onto `tests/unit_tests/{SemaphoreVoting.ts,SemaphoreWhistleblowing.ts}` 
- [ ] Implement usage of `packages/semaphore` onto `tests/cross-chain

**Comment by semaraugusto** [comment]
* unit_tests currently do not need the Semaphore typescript interface. Should integrate the tests with the interface for all unit-tests. Later will change the unit-tests for the `SemaphoreVoting` and `SemaphoreWhistleblowing` to its own interfaces but they're not implemented yet.
* functional tests `test/functional_test/CrossChain.ts` are currently failing. Should integrate with `https://github.com/webb-tools/webb.js/blob/master/packages/test-utils/src/startGanacheServer.ts` and update the interfaces that were used in the test.

**Comment by semaraugusto** [comment]
closed on https://github.com/webb-tools/semaphore-anchor/pull/10
