### ISSUE TITLE
[TASK] Add Typescript implementation of SemaphoreWhistleblowing

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/semaphore-anchor#8]
### Task Checklist 

- [ ] Add Typescript implementation of SemaphoreWhistleblowing
- [ ] Add relevant documentation and usage guides

**Comment by semaraugusto** [comment]
Should add a typescript interface for the SemaphoreVoting contract located at `contracts/extensions/SemaphoreWhistleblowing.sol`
