### ISSUE TITLE
[TASK] Add Typescript implementation of SemaphoreVoting 

### ISSUE THREAD

**Issue by dutterbutter** [webb-tools/semaphore-anchor#9]
### Task Checklist 

- [ ] Add Typescript implementation of SemaphoreVoting
- [ ] Add relevant documentation and usage guides

**Comment by semaraugusto** [comment]
# Overview

Should add a typescript interface for the SemaphoreVoting contract located at `contracts/extensions/SemaphoreVoting.sol`
